In [30]:
!git clone https://github.com/FatimaNdeem/Flyrank-ml-internship..git

Cloning into 'Flyrank-ml-internship.'...
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 139 (delta 50), reused 92 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (139/139), 1.85 MiB | 5.11 MiB/s, done.
Resolving deltas: 100% (50/50), done.

In [31]:
%cd Flyrank-ml-internship.

/content/Flyrank-ml-internship./Flyrank-ml-internship./Flyrank-ml-internship./Flyrank-ml-internship.

In [32]:
!ls data/raw

content_refresh_anonymized.csv

In [33]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/FatimaNdeem/Flyrank-ml-internship./blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

My lane is **Refresh / Content Opportunity Scoring**, which is a **scoring** task. The goal is to assign each webpage a score indicating how strongly it should be considered for a content refresh. Pages with higher scores can then be prioritized by the SEO or content team for review and updating.

In [34]:
print("ML Task Type: Scoring")
print("Dataset Shape:", df.shape)

ML Task Type: Scoring
Dataset Shape: (30000, 44)

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

The target is a predicted content opportunity score that estimates how likely a webpage is to benefit from a content refresh. Since the dataset does not contain a direct label indicating whether a page should be refreshed, the target would be created as a proxy using observed features such as impressions, clicks, search volume, trend direction, and trend percentage.

In [35]:
df.columns

Index(['content_id', 'client_id', 'search_volume', 'competition',
       'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count',
       'char_count', 'provider_used', 'model_used', 'impressions_90d',
       'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d',
       'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d',
       'days_with_impressions', 'days_with_sessions', 'impressions_last_30d',
       'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d',
       'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier',
       'age_tier_order', 'days_since_last_update', 'freshness_tier',
       'word_count_tier', 'char_count_tier', 'ctr', 'avg_position',
       'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier',
       'position_tier', 'trend_direction', 'trend_pct'],
      dtype='object')

## 3. Success metric

*One metric you can defend. What number means 'good'?*

A suitable success metric is **Mean Absolute Error (MAE)** because the task predicts a continuous score. A lower MAE means the predicted scores are closer to the expected values, making the results more useful for prioritizing webpages for content refresh.

In [36]:
print("Chosen Metric: Mean Absolute Error (MAE)")
df[["trend_pct"]].describe()

Chosen Metric: Mean Absolute Error (MAE)

          trend_pct
count  26612.000000
mean      -4.785969
std      473.861780
min     -100.000000
25%      -62.600000
50%      -33.500000
75%        0.000000
max    44900.000000

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

The unit of analysis is **one webpage**. Each row in the dataframe represents one anonymized webpage together with its search performance and content-related features.

In [37]:
print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

A simple rule such as "refresh pages with low traffic" would ignore many important factors that influence webpage performance. Features such as impressions, clicks, search volume, and other content signals interact in complex ways. Machine learning can learn these patterns from historical data and help rank or score webpages for refresh, providing better decision support than a fixed if-else rule.

In [38]:
print("Machine learning combines multiple signals to make better recommendations than a single fixed rule.")

Machine learning combines multiple signals to make better recommendations than a single fixed rule.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.